//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movies()
        {
            this.saloon = new HashSet<saloon>();
        }
    
        public int movie_id { get; set; }
        public Nullable<int> s_id { get; set; }
        public string movie_name { get; set; }
        public string movie_description { get; set; }
        public string movie_beg_date { get; set; }
        public string movie_poster { get; set; }
        public string movie_end_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saloon> saloon { get; set; }
    }
}
