//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_records
    {
        public string saloon_name { get; set; }
        public Nullable<int> movie_id { get; set; }
        public int s_id { get; set; }
        public string movie_name { get; set; }
        public string movie_description { get; set; }
        public string movie_beg_date { get; set; }
        public string movie_poster { get; set; }
        public string movie_end_date { get; set; }
    }
}
