//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saloon
    {
        public int saloon_id { get; set; }
        public string saloon_name { get; set; }
        public string saloon_time { get; set; }
        public Nullable<int> m_id { get; set; }
    
        public virtual movies movies { get; set; }
    }
}
